swagger: "2.0"
info:
  description: API para refrescar token y PreStep
  version: "1.0"
  title: OAuth Methods
basePath: /v1
schemes:
  - https
produces:
  - application/json;charset=UTF-8
consumes:
  - application/x-www-form-urlencoded
paths:
  /{aspsp}/oauth/uri:
    get:
      deprecated: false
      summary: Generar URL de Autorización
      tags:
        - Get URL
      description: Generación de URL para redireccionar el navegador del PSU para que realice la siguiente petición al HUB
      parameters:
        - name: aspsp
          in: path
          required: true
          type: string
          description: Nombre del ASPSP al que desea realizar la petición
        - in: query
          name: state
          type: string
          required: true
          description: Valor opaco generado por el TPP. Usado para prevenir ataques “cross-site request forgery” XSRF.
        - in: query
          name: redirect_uri
          type: string
          required: true
          description: URL de vuelta al HUB donde se informará el código de autorización “code” que será utilizado posteriormente para la obtención del token de acceso.
        - in: query
          name: code_challenge
          type: string
          required: true
          description: Reto PKCE usado para prevenir ataques de inyección de código.
        - in: query
          name: code_challenge_method
          type: string
          required: false
          default: S256
          enum:
            - S256
            - plain
          description: Método para verificar el código que puede ser “plain” o “S256”. Si no se indica nada, se toma "S256" por defecto.
      responses:
        200:
          description: URL de Autorización Enviada
          schema:
            $ref: "#/definitions/ResponseRedirectSuccessfully"
        400:
          description: URL de Autorización fallida
          schema:
            $ref: "#/definitions/ResponseRejected"
  /{aspsp}/oauth/token:
    post:
      deprecated: false
      summary: Obtener Token de Refresco
      tags:
        - RefreshToken
      description: URL para redireccionar el navegador del PSU para que realice la siguiente petición al HUB de RedSys
      parameters:
        - in: path
          name: aspsp
          required: true
          type: string
          description: Nombre del ASPSP al que desea realizar la petición
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/RequestRefreshToken"
      responses:
        200:
          description: Redireccion de Autorización Enviada
          schema:
            $ref: "#/definitions/ResponseRefreshSuccessfully"
        400:
          description: Redireccion de Autorización Enviada
          schema:
            $ref: "#/definitions/ResponseRejected"
definitions:
  RequestRefreshToken:
    type: object
    required:
      - resfresh_token
    properties:
      refresh_token:
        type: string
        pattern: ^.{1,64}$
        description: token para solicitar uno nuevo
        example: tGzv3JOkF0XG5Qx2TlKWIA
  ResponseRedirectSuccessfully:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - attributes
          - type
          - id
        properties:
          attributes:
            type: object
            required:
              - oauth2URL
            properties:
              oauth2URL:
                type: string
                pattern: ^.{1,250}$
                description: URL de redirección
                example: https://www.tpp.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
              requestId:
                type: number
                description: identificador único de operación
                pattern: ˆ[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}
                example: 9179d197-550b-469d-ad2f-385284ccecff
          type:
            type: string
            description: tipo de operación realizada
            example: oauth
          id:
            type: string
            description: identificador de operación. Si no se ha enviado en el cuerpo de la petición se autogenera.
            pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
            example: c51f4677-169f-4479-9f28-da716b5118b6
  ResponseRefreshSuccessfully:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - attributes
          - type
          - id
        properties:
          attributes:
            type: object
            required:
              - access_token
              - token_type
              - expires_in
              - refresh_token
            properties:
              access_token:
                type: string
                pattern: ^.{1,64}$
                description: nuevo Token de acceso
                example: 83kdFZFEjr1zCsicMWBBstate=xyz
              token_type:
                type: string
                description: tipo de token (Bearer)
                enum:
                  - Bearer
                example: Bearer
              expires_in:
                type: number
                description: tiempo en milisegundos de duración del nuevo Token de acceso
                example: 3600
              refresh_token:
                type: string
                pattern: ^.{1,64}$
                description: token de refresco
                example: 28JD3JOkF0NM5Qx2TlCCC=xyz
              requestId:
                type: number
                description: identificador único de operación
                pattern: ˆ[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}
                example: 9179d197-550b-469d-ad2f-385284ccecff
          type:
            type: string
            description: tipo de operación realizada
            example: oauth
          id:
            type: string
            description: identificador de operación. Si no se ha enviado en el cuerpo de la petición se autogenera.
            pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
            example: c51f4677-169f-4479-9f28-da716b5118b6
  ResponseRejected:
    type: object
    required:
      - errors
    properties:
      errors:
        type: array
        items:
          type: object
          required:
            - id
            - status
            - title
            - detail
            - source
          properties:
            id:
              type: string
              description: identificador de operación. Si no se ha enviado en el cuerpo de la petición se autogenera.
              pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
              example: c51f4677-169f-4479-9f28-da716b5118b6
            status:
              type: number
              description: status code
              pattern: ˆ\d{3}$
              example: 400
            title:
              type: string
              description: Título descriptivo del Error
              pattern: ^.{1,50}$
              example: Error
            detail:
              type: string
              description: Detalle del Error de RedSys
              pattern: ^.{1,250}$
              example: Ha fallado la autorización
            source:
              type: object
              properties:
                pointer:
                  type: string
                  description: URL que ha dado el fallo
                  pattern: ˆ\/.{3,20}$
                  example: /{aspsp}/oauth/pre-step
